# Generated by Django 5.2.7 on 2025-10-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_user_telegram_id_alter_user_email_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
