# Generated by Django 5.2.7 on 2025-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expirience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
